runtime: python39

handlers:
  # This configures Google app1 Engine to serve the files in the app1's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app1. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto